### ISSUE TITLE
bunx --bun doesn't work

### ISSUE THREAD

**Issue by rotu** [moonrepo/bun-plugin#12]
Passing the `--bun` flag doesn't work with `bunx`.

E.g. `bunx --bun vite` gives an error like `CACError: Unknown option --bun`.

This seems to be because `bun` has special command line handling when it's called with the name `bunx`. On the other hand, the shim executes it as something like `bun x --bun vite`.

**Comment by rotu** [comment]
Possibly root cause behind https://github.com/oven-sh/bun/issues/4974

**Comment by milesj** [comment]
Bun doesn't provide a `bunx` file, so we have to use `bun x` instead.

Since `--bun` has to come before the `x`, I'm not sure how we would handle that. Unless we always just forced it.

**Comment by rotu** [comment]
I think the easiest is to make the shim like bun does it:
```bash
ln -s $PROTO_HOME/tools/bun/1.0.11/bun $PROTO_HOME/tools/bun/1.0.11/bunx
```

and in proto's shim for `bunx`:
```
exec proto run bun --bin=bunx -- "$@"
```

**Comment by milesj** [comment]
That would have the same problem. Basically the user needs to provide args that go _before and after_ our hardcoded `x`, which isn't possible.

- We either hardcode it to `--bun x` (maybe this is fine?)
- Users can just do `bun --bun x` themselves.

**Comment by rotu** [comment]
No. With the symlink, the bun cli infers the `x` so you don't need to provide it on the command line :-). The above changes *do* work for me on WSL.

**Comment by milesj** [comment]
Ah, ok, so you're saying that bun itself extracts the filename and determines it that way? Interesting. Yeah, let me tinker with that.

**Comment by rotu** [comment]
Exactly. I don’t know zig, but the wrappers when installing via node show this: https://github.com/oven-sh/bun/blob/046d1975192316cb78886269c70c1c292a04a733/packages/bun-release/scripts/upload-npm.ts#L73

I wouldn’t be surprised if you could also accomplish this without the symlink via [`arg0`](https://doc.rust-lang.org/std/process/struct.Command.html#method.arg0), but my gut says that’s a little more fragile.

**Comment by milesj** [comment]
Been messing with this and it works for the bin symlink, but not for the shim, since the shim still executes `bun` under the hood which doesn't pass the "is argv0 bunx" check.

We also can't copy/symlink the bun to bunx from WASM.

**Comment by milesj** [comment]
Works by removing the shim entirely though: https://github.com/moonrepo/bun-plugin/pull/13

**Comment by milesj** [comment]
This works for bins now, but not for shims, going to close.
